config/routes.rb
Rails.application.routes.draw do
  resources :sentences

  root 'sentences#index'

end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
	mount_uploader :translated, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  before_action :set_sentence, only: [:show, :edit, :update, :destroy]

  # GET /sentences
  # GET /sentences.json
  def index
    @sentences = Sentence.all
  end

  # GET /sentences/1
  # GET /sentences/1.json
  def show
  end

  # GET /sentences/new
  def new
    @sentence = Sentence.new
  end

  # GET /sentences/1/edit
  def edit
  end

  # POST /sentences
  # POST /sentences.json
  def create
    @sentence = Sentence.new(sentence_params)

    respond_to do |format|
      if @sentence.save
        format.html { redirect_to @sentence, notice: 'Sentence was successfully created.' }
        format.json { render :show, status: :created, location: @sentence }
      else
        format.html { render :new }
        format.json { render json: @sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sentences/1
  # PATCH/PUT /sentences/1.json
  def update
    respond_to do |format|
      if @sentence.update(sentence_params)
        format.html { redirect_to @sentence, notice: 'Sentence was successfully updated.' }
        format.json { render :show, status: :ok, location: @sentence }
      else
        format.html { render :edit }
        format.json { render json: @sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sentences/1
  # DELETE /sentences/1.json
  def destroy
    @sentence.destroy
    respond_to do |format|
      format.html { redirect_to sentences_url, notice: 'Sentence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sentence
      @sentence = Sentence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sentence_params
      params.require(:sentence).permit(:expression, :translated)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emojiland</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Idea app</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/sentences">Sentences</a></li>
      </ul>
    </div>
  </div>
</nav>

  <div class="container">
  	<%= yield %>
  </div>

<footer>
  <div class="container">
    Rails Girls 2014
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>


</body>
</html>

app/views/sentences/_form.html.erb
<%= form_for (@sentence), :html => {:multipart => true} do |f| %>
  <% if @sentence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sentence.errors.count, "error") %> prohibited this sentence from being saved:</h2>

      <ul>
      <% @sentence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :expression %><br>
    <%= f.text_field :expression %>
  </div>
  <div class="field">
    <%= f.label :translated %><br>
    <%= f.file_field :translated %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sentences/edit.html.erb
<h1>Editing sentence</h1>

<%= render 'form' %>

<%= link_to 'Show', @sentence %> |
<%= link_to 'Back', sentences_path %>

app/views/sentences/index.html.erb
<h1>Translated Emoji Sentences</h1>

<table>
  <thead>
    <tr>
      <th>Expression</th>
      <th>Translated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sentences.each do |sentence| %>
      <tr>
        <td><%= sentence.expression %></td>
        <!-- <td><%= sentence.translated %></td> -->
        <td><%= image_tag(sentence.translated, :width => 50) if sentence.translated.present? %></td>
        <td><%= link_to 'Show', sentence %></td>
        <td><%= link_to 'Edit', edit_sentence_path(sentence) %></td>
        <td><%= link_to 'Destroy', sentence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sentence', new_sentence_path %>

app/views/sentences/new.html.erb
<h1>New sentence</h1>

<%= render 'form' %>

<%= link_to 'Back', sentences_path %>

app/views/sentences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Expression:</strong>
  <%= @sentence.expression %>
</p>

<p>
  <strong>Emojis:</strong>
  <%= image_tag(@sentence.translated, :width => 600) if @sentence.translated.present? %>
</p>

<%= link_to 'Edit', edit_sentence_path(@sentence) %> |
<%= link_to 'Back', sentences_path %>